fix 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,23 @@
 #!/usr/bin/env bash
-# Transfer a file from client to server
-if [ $# -lt 3 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+
+# Check if enough parameters were passed
+if [ $# -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# Assign variables to the parameters passed
+file_path=$1
+server_ip=$2
+username=$3
+ssh_key=$4
+
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/
+
+# Check if the transfer was successful
+if [ $? -eq 0 ]; then
+  echo "File transferred successfully"
 else
-    scp -i "$4" -o stricthostkeychecking=no "$1" "$3@$2":~/
+  echo "Error transferring file"
 fi
